[build]
  command = "yarn build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20"
  NEXT_PUBLIC_RPC_ENDPOINT = "https://rpc.gorbagana.wtf/"
  NEXT_PUBLIC_EXPLORER_URL = "https://trashscan.io"
  NEXT_PUBLIC_TOKEN_PROGRAM_ID = "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA"
  NEXT_PUBLIC_ASSOCIATED_TOKEN_PROGRAM_ID = "ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL"
  NEXT_PUBLIC_METAPLEX_PROGRAM_ID = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"
  NEXT_PUBLIC_IPFS_GATEWAY = "https://ipfs.io"
  NEXT_PUBLIC_DEBUG_IPFS = "true"

# Headers for static assets
[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/_next/image/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Redirects for Next.js
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
