[build]
  command = "yarn build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20"
  NODE_OPTIONS = "--max-old-space-size=4096"
  NEXT_TELEMETRY_DISABLED = "1"
  NODE_ENV = "production"
  NEXT_PUBLIC_RPC_ENDPOINT = "https://rpc.gorbagana.wtf/"
  NEXT_PUBLIC_EXPLORER_URL = "https://trashscan.io"
  NEXT_PUBLIC_TOKEN_PROGRAM_ID = "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA"
  NEXT_PUBLIC_ASSOCIATED_TOKEN_PROGRAM_ID = "ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL"
  NEXT_PUBLIC_METAPLEX_PROGRAM_ID = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"
  NEXT_PUBLIC_IPFS_GATEWAY = "https://ipfs.io"
  NEXT_PUBLIC_DEBUG_IPFS = "true"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@solana/web3.js", "@solana/spl-token", "@storacha/client"]

[[headers]]
  for = "/_next/static/*"
  values = {Cache-Control = "public, max-age=31536000, immutable"}

[[headers]]
  for = "/_next/image/*"
  values = {Cache-Control = "public, max-age=31536000, immutable"}

[[plugins]]
  inputs = {}
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/*"
  status = 200
  to = "/index.html"

[[redirects]]
  from = "/_next/image"
  query = {q = ":quality", url = ":url", w = ":width"}
  status = 200
  to = "/.netlify/images?url=:url&w=:width&q=:quality"

[[redirects]]
  from = "/_ipx/*"
  query = {q = ":quality", url = ":url", w = ":width"}
  status = 200
  to = "/.netlify/images?url=:url&w=:width&q=:quality"
